name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: ğŸ§  Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
    - name: â¬‡ï¸ Checkout source
      uses: actions/checkout@v3
      
    - name: â” Setup node package
      uses: actions/setup-node@v3
      
    - name: ğŸŸ¨ Setup python package
      uses: actions/setup-python@v3
      
    - name: ğŸ“¦ Install and build Node dependencies
      run: npm install
      
    - name: ğŸ Install and build Python dependencies
      run: pip install --upgrade pip #-r requirements.txt
      
    - name: âœï¸ Release Electron app
      run: npm run build
      # uses: samuelmeuli/action-electron-builder@v1.6.0
      # with:
      #   github_token: ${{ secrets.github_token }}