on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  publish-to-npm:
    name: ğŸ§  Publish to npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: â¬‡ï¸ Checkout source
      uses: actions/checkout@v3
      
    - name: â” Setup node
      uses: actions/setup-node@v3
      
    - name: ğŸŸ¨ Setup python
      uses: actions/setup-python@v3
      
    - name: ğŸ“¦ Install dependencies and build
      run: npm install
      
    - name: âœï¸ Publish package
      run: npm publish --provenance

  create-github-release:
    name: ğŸ’ Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-to-npm
    permissions:
      contents: write
    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v3
        
      - name: ğŸ’¡ Create Release
        run: gh release create ${{ github.ref }} --generate-notes
