name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: ğŸ§  Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
    - name: â¬‡ï¸ Checkout source
      uses: actions/checkout@v3
      
    - name: â” Setup node
      uses: actions/setup-node@v3
      
    - name: ğŸŸ¨ Setup python
      uses: actions/setup-python@v3
      
    - name: ğŸ“¦ Install Node dependencies and build
      run: npm install
      
    - name: ğŸ Install Python dependencies
      run: cat requirements.txt | xargs -n 1 pip install
      #run: pip install -r requirements.txt
      
    - name: âœï¸ Release Electron app
      uses: samuelmeuli/action-electron-builder@v1.6.0
    
    - name: ğŸ’ Create Release
      uses: actions/create-release@v1
      with:
          tag_name: ${{ github.ref }}
